./bin/x64/factorio --create /saves/$MAP_NAME && \
sed -i "s/; name=/name=$SERVER_NAME/g" /config/config.ini
sed -i "s/; description=/description=$DESCRIPTION/g" /config/config.ini
sed -i "s/; visibility-public=true/visibility-public=$PUBLIC/g" /config/config.ini
sed -i "s/; visibility-steam=true/visibility-steam=$STEAM/g" /config/config.ini
sed -i "s/; visibility-lan=true/visibility-lan=$LAN/g" /config/config.ini
sed -i "s/; max-players=0/max-players=$MAX_PLAYERS/g" /config/config.ini
sed -i "s/; password=/password=$PASSWORD/g" /config/config.ini
sed -i "s/; enable-whitelist=false/enable-whitelist=$WHITELIST/g" /config/config.ini
./bin/x64/factorio --start-server /saves/$MAP_NAME.zip --config /config/config.ini