services:
    factorio-server:
        image: ghcr.io/planetary-server-manager/planet-factorio:latest
        container_name: factorio-server
        environment:
            - MAP_NAME=new-map
            - SERVER_NAME="Planetary Factorio Server"
            - DESCRIPTION="This is a containerized Factorio server deployed using the Planetary Server Manager."
            - PUBLIC=true
            - LAN=true
            - MAX_PLAYERS=0
            - PASSWORD=cleverpassword
            - WHITELIST=false
            - FACTORIO_USERNAME=
            - FACTORIO_PASSWORD=
            - FACTORIO_TOKEN=
            - PEACEFUL=false
            - SEED=null
        ports:
            - 34197:34197/udp
        volumes:
            - {CONFIG DIRECTORY}:/config
            - {SAVE DIRECTORY}:/saves
        restart: unless-stopped